export const FINANCIAL_AI_TARGETS = {
  PE_MENSUAL_MXN: 405_000,
  VENTAS_OBJETIVO_MENSUAL_MXN: 445_000,
  FOOD_COST_MIN_PCT: 28,
  FOOD_COST_MAX_PCT: 32,
  LABOR_MIN_PCT: 20,
  LABOR_MAX_PCT: 25,
  COSTO_PRIMO_MAX_PCT: 60,
  COMENSALES_OBJETIVO_MES: 1100,
} as const;

export const FINANCIAL_AI_MODEL = 'claude-sonnet-4-20250514';
export const OPENAI_FINANCIAL_AI_MODEL = 'gpt-5.1';
export const FINANCIAL_AI_PROMPT_VERSION = 'v1';
